### ISSUE TITLE
Signed JWT support

### ISSUE THREAD

**Issue by UXabre** [jenkinsci/oic-auth-plugin#202]
### What feature do you want to see added?

Instead of a static secret, that would needed to be maintained, kept secret and rotated, I would also like to see Signed JWT support. This way a supported IDP could verify against an external signed JWT.

I'm looking to implement this in various other projects so, if interested, I could take this project in my scope as well.

**Comment by michael-doubez** [comment]
Hello,

Thanks for the proposal.

I don't understand what you are talking about. The (signed) jwt is obtained as part of the OIDC flow and is associated to a user.
Are you talking a jwt that would be provided to the client instead of the client id and secret ?

Do you have an example of provider using that method ?

**Comment by michael-doubez** [comment]
OK. I see it now in https://openid.net/specs/openid-connect-core-1_0.html#ClientAuthentication
I've never encountered it.

I guess we can expand on the defined in https://github.com/jenkinsci/oic-auth-plugin/blob/64210d160170dcc559a210e9c8055b11bcc7dbc7/src/main/java/org/jenkinsci/plugins/oic/OicSecurityRealm.java#L118 and improve the logic in case of service discovery in https://github.com/jenkinsci/oic-auth-plugin/blob/64210d160170dcc559a210e9c8055b11bcc7dbc7/src/main/java/org/jenkinsci/plugins/oic/WellKnownOpenIDConfigurationResponse.java#L54.

Be aware that the plugin heavily relies on google's authentication implementation, it may make things more difficult to implement.
