### ISSUE TITLE
Dynamic Configuration of Endpoints

### ISSUE THREAD

**Issue by mjmbischoff** [jenkinsci/oic-auth-plugin#33]
"The configuration could be re-read after a certain amount of time, in case the configuration changes on the server." see also #4

**Comment by agentgonzo** [comment]
"in case the configuration changes on the server" - Whilst possible, I think this event is extremely unlikely. If an Identity Provider changed the configuration, then it would break any Relaying Parties that are already using it.
Look at the way that google handles it with https://accounts.google.com/.well-known/openid-configuration

They version the different endpoints, eg:
* authorization_endpoint: "https://accounts.google.com/o/oauth2/v2/auth",
* token_endpoint: "https://www.googleapis.com/oauth2/v4/token",

ie, each time Google makes a breaking change to their configuration/environment, they release it under a new versioned URL, but all previous endpoints continue working as they had before. This is the 'standard' model that cloud-native apps follow - ie, versioned APIs to prevent breaking clients. Due to this, I think that periodically re-reading the configuration is unnecessary.

**Comment by carstenlenz** [comment]
Hey just took a look at this plugin and stumbled over this.
It is not unlikely at all. Many IDProviders for e.g. rotate their public keys on a regular schedule (Okta 
 for example every 3 month) 
A good behaving client will re-read an act accordingly.

**Comment by michael-doubez** [comment]
Keeping the issue for the public key renewal when we verify signed id token.
