### ISSUE TITLE
Latest release breaks build-user-vars-plugin

### ISSUE THREAD

**Issue by LEDfan** [jenkinsci/oic-auth-plugin#343]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
    Jenkins: 2.452.2
    OS: Linux - 5.10.218-208.862.amzn2.x86_64
    Java: 17.0.11 - Eclipse Adoptium (OpenJDK 64-Bit Server VM)
    ---
   build-user-vars-plugin:1.9
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Docker: `jenkins/jenkins:2.452.2-lts-jdk17`

### Reproduction steps

1. install this plugin and configure it (it was already configured in my case, this had been working for a long time) 
2. it breaks when using the latest version of this plugin (version `4.284.v0cc21de03d37`), the version before works fine
3. install `build-user-vars-plugin`****

### Expected Results

During a Jenkins build, the `BUILD_USER_GROUPS` environment variable contains the groups of the user.

### Actual Results

The variable is empty and a message is logged `WARNING	o.j.p.b.v.i.UserIdCauseDeterminant#setJenkinsUserBuildVars: Failed to get groups for user: myuser error: hudson.security.UserMayOrMayNotExistException2: Unable to query user information: myUser Show context`

### Anything else?

Thanks for maintaining this plugin!

**Comment by jglick** [comment]
AFAICT the `oic-auth` plugin is behaving correctly here: it throws `UserMayOrMayNotExistException2` because at this point it does not, in fact, know for sure whether the user exists or not.

The fault lies in the `build-user-vars-plugin` for directly calling `SecurityRealm.loadUserByUsername2` rather than going through `User.getAuthorities`, which is what would fall back to `LastGrantedAuthoritiesProperty` (via `ImpersonatingUserDetailsService2`).

**Comment by michael-doubez** [comment]
I created an report in Jenkins Jira with a ling to this issue.
