### ISSUE TITLE
Session expiring after one hour and refresh token

### ISSUE THREAD

**Issue by trunet** [jenkinsci/oic-auth-plugin#39]
I didn't find a way to define how long the session should be active.

Can we use JWT refresh token to auto renew the token?

**Comment by mjmbischoff** [comment]
Currently it simply does the authentication with the openid provider and then control is back to Jenkins. I think Jenkins then delegates things to the container with respect to session logout. When session is expired your basically back at the beginning.

It might be worth it to explore extending things so that the Jenkins session is more tied to the Openid Provider session and perhaps explicitly recheck if a user does 'critical' operations.

It does mean Jenkins would be more depended on the openid provider to available which might be a good trade off for some while others prefer more separation. This could be addressed by additional configuration.

Can you elaborate on your usecase?

**Comment by trunet** [comment]
Thanks for the explanation.

My use case is the users logging in, and not having to login again every hour.

Per your explanation, is there a way to dynamically set jenkins session-timeout based on the ticket expiration (in my case is 24 hours)?

**Comment by mjmbischoff** [comment]
https://stackoverflow.com/questions/26407541/increase-the-jenkins-login-timeout should point you in the right direction.

Leaving this open to contemplate options with respect to refreshing session and/or auto-login
