### ISSUE TITLE
Ssl verification fail with new version of Bouncy Castle API Plugin 2.17

### ISSUE THREAD

**Issue by ebesson** [jenkinsci/oic-auth-plugin#42]
When Jenkins is updated with the new version of Bouncy Castle API Plugin (2.17), ssl verification fail. The workaround is to disabled ssl verification.

**Comment by mjmbischoff** [comment]
got any error logs or stacktraces? @ebesson

**Comment by ebesson** [comment]
@mjmbischoff , I'll will try to send to you errors logs and stacktraces tomorrow.

**Comment by mjmbischoff** [comment]
Ok @ebesson sorry for wait, I wanted to double check before I blame a problem on something other then my plugin.

Looking at the stacktrace it would seem that setting up the TLS connection is without issue and that there's a correct/valid certificate. The problem is that Jenkins/openid connect plugin/java doesn't trust the certificate as there's no certified path. This is generally due to a missing intermediate cert known to the client(jenkins) or send by the server(your openid connect server) in the TLS handshake.

Your solution could be:
- to modify the openid connect server to send the intermediates
- to modify the cacerts on the jenkins server to trust the cert directly or certificates higher up in the chain.
- swap the certificate on the openid connect server using something thats trusted by default

If it worked before and you only changed the Jenkins installation then most likely the cacerts file changed. This could have a very good reason, like the ROOT cert private key being compromised or it using an outdated (no longer considered safe) crypto algorithm. Given the latter they generally reissue new certs for free.

It's a little hard for me to assert whats going wrong from over here. What I did try is running a Jenkins with bouncy castle 2.17 and checking that it worked with the plugin.

**Comment by mjmbischoff** [comment]
Going to assume the issue got resolved should anyone hit the same sort of problem and thinks it's related to the plugin please open a new issue referring to this one.
