### ISSUE TITLE
Token Refresh fails when Use Root URL From Request is enabled

### ISSUE THREAD

**Issue by ZIRAKrezovic** [jenkinsci/oic-auth-plugin#457]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
Jenkins: 2.479.1
OS: Linux - 5.14.0-427.40.1.el9_4.x86_64
Java: 17.0.13 - Red Hat, Inc. (OpenJDK 64-Bit Server VM)
---
Office-365-Connector:5.0.0
active-directory:2.37
ansicolor:1.0.5
antisamy-markup-formatter:162.v0e6ec0fcfcf6
apache-httpcomponents-client-4-api:4.5.14-208.v438351942757
apache-httpcomponents-client-5-api:5.4-124.v31e2987e48f4
asm-api:9.7.1-97.v4cc844130d97
authentication-tokens:1.119.v50285141b_7e1
bitbucket:254.v9d8ec33a_7a_42
bootstrap5-api:5.3.3-1
bouncycastle-api:2.30.1.78.1-248.ve27176eb_46cb_
branch-api:2.1197.vfa_d0c47c267d
build-blocker-plugin:166.vc82fc20b_a_ed6
build-name-setter:2.4.3
build-timeout:1.33
caffeine-api:3.1.8-133.v17b_1ff2e0599
checks-api:2.2.1
cloud-stats:336.v788e4055508b_
cloudbees-folder:6.955.v81e2a_35c08d3
cobertura:1.17
code-coverage-api:4.99.0
commons-lang3-api:3.17.0-84.vb_b_938040b_078
commons-text-api:1.12.0-129.v99a_50df237f7
conditional-buildstep:1.4.3
configuration-as-code:1873.vea_5814ca_9c93
coverage:1.16.1
credentials:1389.vd7a_b_f5fa_50a_2
credentials-binding:687.v619cb_15e923f
dashboard-view:2.517.v776a_b_811a_b_4e
data-tables-api:2.1.8-1
display-url-api:2.209.v582ed814ff2f
docker-commons:443.v921729d5611d
docker-java-api:3.4.0-94.v65ced49b_a_7d5
durable-task:577.v2a_8a_4b_7c0247
echarts-api:5.5.1-4
eddsa-api:0.3.0-4.v84c6f0f4969e
email-ext:1844.v3ea_a_b_842374a_
embeddable-build-status:487.va_0ef04c898a_2
font-awesome-api:6.6.0-2
forensics-api:2.6.0
git:5.6.0
git-client:6.1.0
git-parameter:0.10.0
github:1.40.0
github-api:1.321-478.vc9ce627ce001
github-branch-source:1807.v50351eb_7dd13
gitlab-plugin:1.9.5
gradle:2.13.1
gson-api:2.11.0-85.v1f4e87273c33
htmlpublisher:1.36
instance-identity:201.vd2a_b_5a_468a_a_6
ionicons-api:74.v93d5eb_813d5f
jackson2-api:2.17.0-379.v02de8ec9f64c
jakarta-activation-api:2.1.3-1
jakarta-mail-api:2.1.3-1
javax-activation-api:1.2.0-7
javax-mail-api:1.6.2-10
jaxb:2.3.9-1
jersey2-api:2.44-151.v6df377fff741
jjwt-api:0.11.5-112.ve82dfb_224b_a_d
joda-time-api:2.13.0-93.v9934da_29b_a_e9
jquery3-api:3.7.1-2
jsch:0.2.16-86.v42e010d9484b_
json-api:20240303-101.v7a_8666713110
json-path-api:2.9.0-118.v7f23ed82a_8b_8
junit:1307.vdd5b_2646279e
ldap:764.v4d0d3599e9c2
locale:544.v5ee877a_46b_90
mailer:489.vd4b_25144138f
matrix-auth:3.2.3
matrix-project:840.v812f627cb_578
mercurial:1260.vdfb_723cdcc81
mina-sshd-api-common:2.14.0-133.vcc091215a_358
mina-sshd-api-core:2.14.0-133.vcc091215a_358
oic-auth:4.418.vccc7061f5b_6d
okhttp-api:4.11.0-181.v1de5b_83857df
pam-auth:1.11
parameterized-trigger:806.vf6fff3e28c3e
pipeline-build-step:540.vb_e8849e1a_b_d8
pipeline-github-lib:61.v629f2cc41d83
pipeline-graph-analysis:216.vfd8b_ece330ca_
pipeline-groovy-lib:744.v5b_556ee7c253
pipeline-input-step:495.ve9c153f6067b_
pipeline-milestone-step:119.vdfdc43fc3b_9a_
pipeline-model-api:2.2214.vb_b_34b_2ea_9b_83
pipeline-model-definition:2.2214.vb_b_34b_2ea_9b_83
pipeline-model-extensions:2.2214.vb_b_34b_2ea_9b_83
pipeline-rest-api:2.34
pipeline-stage-step:312.v8cd10304c27a_
pipeline-stage-tags-metadata:2.2214.vb_b_34b_2ea_9b_83
pipeline-stage-view:2.34
plain-credentials:183.va_de8f1dd5a_2b_
plugin-util-api:5.1.0
prism-api:1.29.0-17
resource-disposer:0.25
role-strategy:743.v142ea_b_d5f1d3
run-condition:1.7
scm-api:698.v8e3b_c788f0a_6
script-security:1367.vdf2fc45f229c
snakeyaml-api:2.3-123.v13484c65210a_
ssh-agent:376.v8933585c69d3
ssh-credentials:343.v884f71d78167
ssh-slaves:2.973.v0fa_8c0dea_f9f
sshd:3.330.vc866a_8389b_58
structs:338.v848422169819
timestamper:1.28
token-macro:400.v35420b_922dcb_
trilead-api:2.147.vb_73cc728a_32e
uno-choice:2.8.4
variant:60.v7290fc0eb_b_cd
workflow-aggregator:600.vb_57cdd26fdd7
workflow-api:1336.vee415d95c521
workflow-basic-steps:1058.vcb_fc1e3a_21a_9
workflow-cps:3990.vd281dd77a_388
workflow-durable-task-step:1371.vb_7cec8f3b_95e
workflow-job:1460.v28178c1ef6e6
workflow-multibranch:795.ve0cb_1f45ca_9a_
workflow-scm-step:427.v4ca_6512e7df1
workflow-step-api:678.v3ee58b_469476
workflow-support:930.vf51d22b_ce488
ws-cleanup:0.48
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Linux

### Reproduction steps

Simply configure Jenkins OIC Plugin with Token Refresh (or with discovery that supports refresh) and enable "Use Root URL from request" config option

### Expected Results

After my token expires, it is renewed transparently

### Actual Results

I get an error page, with following exception stack trace in the logs

```
java.lang.IllegalStateException: cannot call getRootUrlFromRequest from outside a request handling thread
        at jenkins.model.Jenkins.getRootUrlFromRequest(Jenkins.java:2574)
        at PluginClassLoader for oic-auth//org.jenkinsci.plugins.oic.OicSecurityRealm.getRootUrl(OicSecurityRealm.java:1231)
        at PluginClassLoader for oic-auth//org.jenkinsci.plugins.oic.OicSecurityRealm.ensureRootUrl(OicSecurityRealm.java:1238)
        at PluginClassLoader for oic-auth//org.jenkinsci.plugins.oic.OicSecurityRealm.buildOAuthRedirectUrl(OicSecurityRealm.java:1251)
        at PluginClassLoader for oic-auth//org.jenkinsci.plugins.oic.OicSecurityRealm.buildOidcClient(OicSecurityRealm.java:683)
        at PluginClassLoader for oic-auth//org.jenkinsci.plugins.oic.OicSecurityRealm.refreshExpiredToken(OicSecurityRealm.java:1398)
        at PluginClassLoader for oic-auth//org.jenkinsci.plugins.oic.OicSecurityRealm.handleTokenExpiration(OicSecurityRealm.java:1362)
        at PluginClassLoader for oic-auth//org.jenkinsci.plugins.oic.OicSecurityRealm$1.doFilter(OicSecurityRealm.java:861)
        at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:101)
```

**Comment by herglotzmarco** [comment]
I observe something similar. For me the stacktraces looks a little different, but it seems like the Root Cause is identical: It tries to refresh a token without having an http request at hand. For me this causes the Jenkins UI being broken beyond repair. You have to manually clear the session cookie in the browser, otherwise there seems to be no way to get out of the broken state.

` java.lang.NullPointerException: Cannot invoke "javax.servlet.http.HttpServletRequest.getSession(boolean)" because "req" is null
jenkins-1  |    at PluginClassLoader for oic-auth//org.jenkinsci.plugins.oic.OicSecurityRealm.redirectToLoginUrl(OicSecurityRealm.java:1379)
jenkins-1  |    at PluginClassLoader for oic-auth//org.jenkinsci.plugins.oic.OicSecurityRealm.refreshExpiredToken(OicSecurityRealm.java:1478)
jenkins-1  |    at PluginClassLoader for oic-auth//org.jenkinsci.plugins.oic.OicSecurityRealm.handleTokenExpiration(OicSecurityRealm.java:1366)
jenkins-1  |    at PluginClassLoader for oic-auth//org.jenkinsci.plugins.oic.OicSecurityRealm$1.doFilter(OicSecurityRealm.java:861)
jenkins-1  |    at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:101)
jenkins-1  |    at io.jenkins.servlet.FilterChainWrapper$1.doFilter(FilterChainWrapper.java:28)
jenkins-1  |    at hudson.security.ChainedServletFilter2$1.doFilter(ChainedServletFilter2.java:94)
jenkins-1  |    at jenkins.security.AcegiSecurityExceptionFilter.doFilter(AcegiSecurityExceptionFilter.java:52)
jenkins-1  |    at hudson.security.ChainedServletFilter2$1.doFilter(ChainedServletFilter2.java:99)
jenkins-1  |    at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:54)
jenkins-1  |    at hudson.security.ChainedServletFilter2$1.doFilter(ChainedServletFilter2.java:99)
jenkins-1  |    at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:126)
jenkins-1  |    at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:120)
jenkins-1  |    at hudson.security.ChainedServletFilter2$1.doFilter(ChainedServletFilter2.java:99)
jenkins-1  |    at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:100)
jenkins-1  |    at hudson.security.ChainedServletFilter2$1.doFilter(ChainedServletFilter2.java:99)
jenkins-1  |    at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:110)
jenkins-1  |    at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:101)
jenkins-1  |    at hudson.security.ChainedServletFilter2$1.doFilter(ChainedServletFilter2.java:99)
jenkins-1  |    at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:227)
jenkins-1  |    at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:221)
jenkins-1  |    at hudson.security.ChainedServletFilter2$1.doFilter(ChainedServletFilter2.java:99)
jenkins-1  |    at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:98)
jenkins-1  |    at hudson.security.ChainedServletFilter2$1.doFilter(ChainedServletFilter2.java:99)
jenkins-1  |    at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:117)
jenkins-1  |    at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:87)
jenkins-1  |    at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:63)
jenkins-1  |    at hudson.security.ChainedServletFilter2$1.doFilter(ChainedServletFilter2.java:99)
jenkins-1  |    at hudson.security.ChainedServletFilter2.doFilter(ChainedServletFilter2.java:111)
jenkins-1  |    at io.jenkins.servlet.FilterWrapper$2.doFilter(FilterWrapper.java:83)
jenkins-1  |    at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:101)
jenkins-1  |    at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:113)
jenkins-1  |    at io.jenkins.servlet.FilterWrapper$1.doFilter(FilterWrapper.java:42)
jenkins-1  |    at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:173)
jenkins-1  |    at Jenkins Main ClassLoader//org.eclipse.jetty.ee9.servlet.FilterHolder.doFilter(FilterHolder.java:202)
jenkins-1  |    at Jenkins Main ClassLoader//org.eclipse.jetty.ee9.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1638)
jenkins-1  |    at org.kohsuke.stapler.UncaughtExceptionFilter.doFilter(UncaughtExceptionFilter.java:26)
jenkins-1  |    at Jenkins Main ClassLoader//org.eclipse.jetty.ee9.servlet.FilterHolder.doFilter(FilterHolder.java:202)
jenkins-1  |    at Jenkins Main ClassLoader//org.eclipse.jetty.ee9.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1638)
jenkins-1  |    at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:86)
jenkins-1  |    at Jenkins Main ClassLoader//org.eclipse.jetty.ee9.servlet.FilterHolder.doFilter(FilterHolder.java:202)
jenkins-1  |    at Jenkins Main ClassLoader//org.eclipse.jetty.ee9.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1638)
jenkins-1  |    at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:31)
jenkins-1  |    at Jenkins Main ClassLoader//org.eclipse.jetty.ee9.servlet.FilterHolder.doFilter(FilterHolder.java:202)
jenkins-1  |    at Jenkins Main ClassLoader//org.eclipse.jetty.ee9.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1638)
jenkins-1  |    at jenkins.security.SuspiciousRequestFilter.doFilter(SuspiciousRequestFilter.java:38)
jenkins-1  |    at Jenkins Main ClassLoader//org.eclipse.jetty.ee9.servlet.FilterHolder.doFilter(FilterHolder.java:202)
jenkins-1  |    at Jenkins Main ClassLoader//org.eclipse.jetty.ee9.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1638)
jenkins-1  |    at Jenkins Main ClassLoader//org.eclipse.jetty.ee9.servlet.ServletHandler.doHandle(ServletHandler.java:526)
jenkins-1  |    at Jenkins Main ClassLoader//org.eclipse.jetty.ee9.nested.ScopedHandler.handle(ScopedHandler.java:127)
jenkins-1  |    at Jenkins Main ClassLoader//org.eclipse.jetty.ee9.security.SecurityHandler.handle(SecurityHandler.java:574)
jenkins-1  |    at Jenkins Main ClassLoader//org.eclipse.jetty.ee9.nested.HandlerWrapper.handle(HandlerWrapper.java:124)
jenkins-1  |    at Jenkins Main ClassLoader//org.eclipse.jetty.ee9.nested.ScopedHandler.nextHandle(ScopedHandler.java:197)
jenkins-1  |    at Jenkins Main ClassLoader//org.eclipse.jetty.ee9.nested.SessionHandler.doHandle(SessionHandler.java:609)
jenkins-1  |    at Jenkins Main ClassLoader//org.eclipse.jetty.ee9.nested.ScopedHandler.nextHandle(ScopedHandler.java:195)
jenkins-1  |    at Jenkins Main ClassLoader//org.eclipse.jetty.ee9.nested.ContextHandler.doHandle(ContextHandler.java:1035)
jenkins-1  |    at Jenkins Main ClassLoader//org.eclipse.jetty.ee9.nested.ScopedHandler.nextScope(ScopedHandler.java:164)
jenkins-1  |    at Jenkins Main ClassLoader//org.eclipse.jetty.ee9.servlet.ServletHandler.doScope(ServletHandler.java:483)
jenkins-1  |    at Jenkins Main ClassLoader//org.eclipse.jetty.ee9.nested.ScopedHandler.nextScope(ScopedHandler.java:162)
jenkins-1  |    at Jenkins Main ClassLoader//org.eclipse.jetty.ee9.nested.SessionHandler.doScope(SessionHandler.java:586)
jenkins-1  |    at Jenkins Main ClassLoader//org.eclipse.jetty.ee9.nested.ScopedHandler.nextScope(ScopedHandler.java:162)
jenkins-1  |    at Jenkins Main ClassLoader//org.eclipse.jetty.ee9.nested.ContextHandler.doScope(ContextHandler.java:956)
jenkins-1  |    at Jenkins Main ClassLoader//org.eclipse.jetty.ee9.nested.ScopedHandler.handle(ScopedHandler.java:125)
jenkins-1  |    at Jenkins Main ClassLoader//org.eclipse.jetty.ee9.nested.ContextHandler.handle(ContextHandler.java:1694)
jenkins-1  |    at Jenkins Main ClassLoader//org.eclipse.jetty.ee9.nested.HttpChannel$RequestDispatchable.dispatch(HttpChannel.java:1576)
jenkins-1  |    at Jenkins Main ClassLoader//org.eclipse.jetty.ee9.nested.HttpChannel.dispatch(HttpChannel.java:738)
jenkins-1  |    at Jenkins Main ClassLoader//org.eclipse.jetty.ee9.nested.HttpChannel.handle(HttpChannel.java:511)
jenkins-1  |    at Jenkins Main ClassLoader//org.eclipse.jetty.ee9.nested.ContextHandler$CoreContextHandler$CoreToNestedHandler.handle(ContextHandler.java:2862)
jenkins-1  |    at Jenkins Main ClassLoader//org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1060)
jenkins-1  |    at Jenkins Main ClassLoader//org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:597)
jenkins-1  |    at Jenkins Main ClassLoader//org.eclipse.jetty.server.Server.handle(Server.java:181)
jenkins-1  |    at Jenkins Main ClassLoader//org.eclipse.jetty.server.internal.HttpChannelState$HandlerInvoker.run(HttpChannelState.java:661)
jenkins-1  |    at Jenkins Main ClassLoader//org.eclipse.jetty.server.internal.HttpConnection.onFillable(HttpConnection.java:406)
jenkins-1  |    at Jenkins Main ClassLoader//org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:322)
jenkins-1  |    at Jenkins Main ClassLoader//org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:99)
jenkins-1  |    at Jenkins Main ClassLoader//org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
jenkins-1  |    at Jenkins Main ClassLoader//org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:478)
jenkins-1  |    at Jenkins Main ClassLoader//org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:441)
jenkins-1  |    at Jenkins Main ClassLoader//org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:293)
jenkins-1  |    at Jenkins Main ClassLoader//org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.run(AdaptiveExecutionStrategy.java:201)
jenkins-1  |    at Jenkins Main ClassLoader//org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:311)
jenkins-1  |    at Jenkins Main ClassLoader//org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:979)
jenkins-1  |    at Jenkins Main ClassLoader//org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1209)
jenkins-1  |    at Jenkins Main ClassLoader//org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1164)
jenkins-1  |    at java.base/java.lang.Thread.run(Unknown Source)
`

**Comment by akuntsch** [comment]
> I observe something similar. For me the stacktraces looks a little different, but it seems like the Root Cause is identical: It tries to refresh a token without having an http request at hand. For me this causes the Jenkins UI being broken beyond repair. You have to manually clear the session cookie in the browser, otherwise there seems to be no way to get out of the broken state.

Same here. Seems like that Stapler request is null at 
https://github.com/jenkinsci/oic-auth-plugin/blob/7d45bab6ad3d9751edcd78f0f6db94e84f510655/src/main/java/org/jenkinsci/plugins/oic/OicSecurityRealm.java#L1478

Is there any reason we don't use the `httpRequest` that's passed to the method?
https://github.com/jenkinsci/oic-auth-plugin/blob/7d45bab6ad3d9751edcd78f0f6db94e84f510655/src/main/java/org/jenkinsci/plugins/oic/OicSecurityRealm.java#L1396

**Comment by tj-cisco** [comment]
Seeing the same issue without "Use Root URL From Request" enabled

```
java.lang.NullPointerException: Cannot invoke "javax.servlet.http.HttpServletRequest.getSession(boolean)" because "req" is null
	at PluginClassLoader for oic-auth//org.jenkinsci.plugins.oic.OicSecurityRealm.redirectToLoginUrl(OicSecurityRealm.java:1379)
	at PluginClassLoader for oic-auth//org.jenkinsci.plugins.oic.OicSecurityRealm.refreshExpiredToken(OicSecurityRealm.java:1478)
	at PluginClassLoader for oic-auth//org.jenkinsci.plugins.oic.OicSecurityRealm.handleTokenExpiration(OicSecurityRealm.java:1366)
	at PluginClassLoader for oic-auth//org.jenkinsci.plugins.oic.OicSecurityRealm$1.doFilter(OicSecurityRealm.java:861)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:101)
```
