### ISSUE TITLE
Dispaly of Keycloak Authentication Plugin Window doesn't work!

### ISSUE THREAD

**Issue by ewasos** [jenkinsci/oic-auth-plugin#68]
I can't see Keycloak Authentication Plugin Window in Jenkins Global Configuration, so impossible for me to insert keycloak configuartion json. I run 2.150.2 jenkins on docker.

![image](https://user-images.githubusercontent.com/25526770/54677876-212c1400-4b04-11e9-8159-c4d9b7f30b66.png)

Any solution?

**Comment by mjmbischoff** [comment]
I think you mixed up the keycloak and the openid connect plugin. Since keycloak supports openid connect it should work. If you install this plugin then it should give you the option of 'login with openid connect'.

Otherwise I would direct you to the plugin maintainer of the keycloak plugin. I think their issue tracker is here: https://github.com/devlauer/jenkins-keycloak-plugin but I could be wrong.

**Comment by michael-doubez** [comment]
Closing this issue as there is no further question from OP
